=# ghostty.conf
# By Johnyyd (https://github.com/Johnyyd)


# Background and foreground colors
background = #000000
foreground = #BAC8B1
background-opacity = 0.20
cursor-color = #BAC8B1
selection-background = #8FA4AB
selection-foreground = #000000

# Standard colors
palette = 0=#000000
palette = 1=#D94F4F
palette = 2=#6F9C97
palette = 3=#FFB347
palette = 4=#4D5F64
palette = 5=#FF7A3D
palette = 6=#6F9C97
palette = 7=#BAC8B1

# Bright colors
palette = 8=#000000
palette = 9=#D94F4F
palette = 10=#6F9C97
palette = 11=#FFB347
palette = 12=#4D5F64
palette = 13=#FF7A3D
palette = 14=#6F9C97
palette = 15=#BAC8B1