# hyprlock.conf
# By Johnyyd (https://github.com/Johnyyd)
#

$color = rgba(143, 164, 171, 1)
$inner_color = rgba(143, 164, 171, 0.66)
$outer_color = rgba(53, 49, 60, 1)
$font_color = rgba(186, 200, 177, 1)
$placeholder_color = rgba(186, 200, 177, 0.7)
$check_color = rgba(111, 156, 151, 1)