foreground            #BAC8B1
background            #000000
background_opacity    0.80

selection_foreground  #000000
selection_background #8FA4AB
cursor                #BAC8B1
cursor_text_color     #000000

active_border_color   #8FA4AB
active_tab_background #8FA4AB

color0 #000000
color1 #D94F4F
color2 #6F9C97
color3 #FFB347
color4 #4D5F64
color5 #FF7A3D
color6 #6F9C97
color7 #BAC8B1
color8 #A08F82
color9 #D94F4F
color10 #6F9C97
color11 #FFB347
color12 #4D5F64
color13 #FF7A3D
color14 #6F9C97
color15 #BAC8B1
