# kitty.conf
# By Johnyyd (https://github.com/Johnyyd)
#

background            #000000
foreground            #BAC8B1
background_opacity    0.30
background_blur 1

selection_foreground  #000000
selection_background  #8FA4AB
cursor                #BAC8B1
cursor_text_color     #000000
active_border_color   #8FA4AB
active_tab_background #8FA4AB

# black
color0  #000000
color8  #000000

# red
color1  #D94F4F
color9  #D94F4F

# green
color2  #6F9C97
color10 #6F9C97

# yellow
color3  #FFB347
color11 #FFB347

# blue
color4  #4D5F64
color12 #4D5F64

# magenta
color5  #FF7A3D
color13 #FF7A3D

#cyan
color6  #6F9C97
color14 #6F9C97

#white
color7  #BAC8B1
color15 #BAC8B1